##########
# site.title

title: 'One Jekyll Starter Theme'
description: A clean and simple Jekyll starter theme.

##########
# settings

markdown: kramdown

sass:
  sass_dir: _sass
  style:    compressed

exclude:
- README.md
- LICENSE.md